[package]
name = "csven"
version = "0.1.20"
edition = "2024"

[dependencies]
gtk = {version= "0.10.2", package="gtk4", features=["v4_2"]}
adw = { version = "0.8.1", package = "libadwaita", features = ["v1_7"]} 
